[package]
name = "file_sync_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-debouncer-full = "0.3.1"
notify = "6.1.1"
