name: Build, Test, lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        run: |
          rustup update
          rustup default stable

      - name: Check Formatting
        run: |
          rustup component add rustfmt
          cargo fmt -- --check

      - name: Lint with Clippy
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings

      - name: Run Tests
        run: |
          cargo test
